/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_16bit_2_6 (
    input a,
    input b,
    input [0:0] alufn,
    input [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    v = (a & (b ^ alufn[0+0-:1]) & ~(s[15+0-:1])) | (~(a) & ~(b ^ alufn[0+0-:1]) & s[15+0-:1]);
    n = s[15+0-:1];
    z = (~|s[0+15-:16]);
  end
endmodule
