/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_16bit_2_6 (
    input [15:0] a,
    input [15:0] b,
    input [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    v = (a[15+0-:1] | b[15+0-:1] | ~(s[15+0-:1])) & (~(a[15+0-:1]) | ~(b[15+0-:1]) | s[15+0-:1]);
    n = s[15+0-:1];
    z = (~|s[0+15-:16]);
  end
endmodule
