/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare16bit_9 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] s
  );
  
  
  
  always @* begin
    s[0+15-:16] = 1'h0;
    if (alufn[1+1-:2] == 2'h2) begin
      s[0+0-:1] = n ^ v;
    end
    if (alufn[1+1-:2] == 2'h1) begin
      s[0+0-:1] = z;
    end
    if (alufn[1+1-:2] == 2'h3) begin
      s[0+0-:1] = (n ^ v) | z;
    end
  end
endmodule
