/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_16bit_8 (
    input [15:0] a,
    input [3:0] b,
    input [1:0] alufn,
    output reg [15:0] s
  );
  
  
  
  always @* begin
    s[0+15-:16] = 1'h0;
    if (alufn[0+1-:2] == 2'h3) begin
      s[0+15-:16] = $signed(a[0+15-:16]) >>> b[0+3-:4];
    end
    if (alufn[0+1-:2] == 2'h1) begin
      s[0+15-:16] = a[0+15-:16] >> b[0+3-:4];
    end
    if (alufn[0+1-:2] == 2'h2) begin
      s[0+15-:16] = a[0+15-:16] <<< b[0+3-:4];
    end
    if (alufn[0+1-:2] == 2'h0) begin
      s[0+15-:16] = a[0+15-:16] << b[0+3-:4];
    end
  end
endmodule
