/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_16bit_7 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] s
  );
  
  
  
  always @* begin
    s[0+15-:16] = 1'h0;
    if (alufn[0+3-:4] == 10'h3e8) begin
      s[0+15-:16] = a[0+15-:16] & b[0+15-:16];
    end
    if (alufn[0+3-:4] == 7'h6f) begin
      s[0+15-:16] = ~(a[0+15-:16] & b[0+15-:16]);
    end
    if (alufn[0+3-:4] == 11'h456) begin
      s[0+15-:16] = a[0+15-:16] | b[0+15-:16];
    end
    if (alufn[0+3-:4] == 1'h1) begin
      s[0+15-:16] = ~(a[0+15-:16] | b[0+15-:16]);
    end
    if (alufn[0+3-:4] == 7'h6e) begin
      s[0+15-:16] = a[0+15-:16] ^ b[0+15-:16];
    end
    if (alufn[0+3-:4] == 10'h3f2) begin
      s[0+15-:16] = a[0+15-:16];
    end
    if (alufn[0+3-:4] == 7'h65) begin
      s[0+15-:16] = b[0+15-:16];
    end
  end
endmodule
